on:
  push:
  pull_request:
  schedule:
    - cron: '17 10 * * 6'

name: ci

jobs:
  test_latest:
    name: Build & Test (latest Rust version)
    # runs-on cannot be parameterized yet: https://stackoverflow.com/questions/71961921/specify-runner-to-be-used-depending-on-condition-in-a-github-actions-workflow
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-ci
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked

  test_min:
    name: Build & Test (min Rust version)
    # runs-on cannot be parameterized yet: https://stackoverflow.com/questions/71961921/specify-runner-to-be-used-depending-on-condition-in-a-github-actions-workflow
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-ci
        with:
          rust-version: 1.70.0
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-ci
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-ci
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --locked --all-targets -- -D warnings
